/*  axil-regfile.c - The simplest kernel module.

* Copyright (C) 2013-2022 Xilinx, Inc
* Copyright (c) 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License along
*   with this program. If not, see <http://www.gnu.org/licenses/>.

*/
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>
#include <linux/platform_device.h>

MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Xilinx Inc.");
MODULE_DESCRIPTION
    ("axil-regfile - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "axil-regfile"

#define REGF_ID      0x00
#define REGF_CTRL    0x08
#define REGF_TPG_CFG 0x0C
#define REGF_STATUS  0x10

struct axil_regfile_local {
        unsigned long mem_start;
        unsigned long mem_end;
        void __iomem *base_addr;
};

static ssize_t ctrl_store(struct device *dev, struct device_attribute *attr, const char *buf, size_t count) {
	uint32_t enable, mux;
	struct axil_regfile_local *lp = dev_get_drvdata(dev);

	if (sscanf(buf, "%d %d", &enable, &mux) != 2) {
		return -EINVAL;
	}

	uint32_t ctrl = (enable & 0x1) | ((mux & 0x1) << 1);
	iowrite32(ctrl, lp->base_addr + REGF_CTRL);

	return count; 
}

static ssize_t ctrl_show(struct device *dev, struct device_attribute *attr, char *buf) {
       	struct axil_regfile_local *lp = dev_get_drvdata(dev);
	uint32_t ctrl = ioread32(lp->base_addr + REGF_CTRL);

	return sprintf(buf, "enable : %u, mux : %u\n", ctrl & 1, (ctrl >>  1) & 1);	
}
static DEVICE_ATTR_RW(ctrl);

static ssize_t id_show(struct device *dev, struct device_attribute *attr, char *buf)
{
        struct axil_regfile_local *lp = dev_get_drvdata(dev);
        return sprintf(buf, "0x%08x\n", ioread32(lp->base_addr + REGF_ID));
}
static DEVICE_ATTR_RO(id);

static int axil_regfile_probe(struct platform_device *pdev)
{
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct axil_regfile_local *lp = NULL;

	int rc = 0;
	dev_info(dev, "Device Tree Probing\n");
	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "invalid address\n");
		return -ENODEV;
	}
	lp = (struct axil_regfile_local *) kmalloc(sizeof(struct axil_regfile_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate axil-regfile device\n");
		return -ENOMEM;
	}
	dev_set_drvdata(dev, lp);
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;

	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}

	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	if (!lp->base_addr) {
		dev_err(dev, "axil-regfile: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}
	rc = device_create_file(dev, &dev_attr_id);
	if (rc) {
		dev_err(dev, "failed to create sysfs 'id'\n");
	}
	rc = device_create_file(dev, &dev_attr_ctrl);
	if (rc) {
		dev_err(dev, "failed to create sysfs 'ctrl'\n");
	}
	

	return 0;
error2:
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static void axil_regfile_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct axil_regfile_local *lp = dev_get_drvdata(dev);
	iounmap(lp->base_addr);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
}

#ifdef CONFIG_OF
static struct of_device_id axil_regfile_of_match[] = {
	{ .compatible = "xlnx,axil-regfile-1.0", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, axil_regfile_of_match);
#else
# define axil_regfile_of_match
#endif


static struct platform_driver axil_regfile_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= axil_regfile_of_match,
	},
	.probe		= axil_regfile_probe,
	.remove		= axil_regfile_remove,
};

static int __init axil_regfile_init(void) {
	printk("<1>Hello axil-regfile.\n");
	return platform_driver_register(&axil_regfile_driver);
}


static void __exit axil_regfile_exit(void) {
	platform_driver_unregister(&axil_regfile_driver);
	printk(KERN_ALERT "axil-regfile exit.\n");
}

module_init(axil_regfile_init);
module_exit(axil_regfile_exit);
